/** Phase 1 shared-expense hub. Data is shared server-side, never stored as contacts locally. */
import { useCallback, useEffect, useState } from 'react';
import { Check, CirclePlus, FolderHeart, Search, UserPlus, Users, X } from 'lucide-react';
import { CURRENCIES } from '@expense/shared';
import { api } from '../lib/api.js';
import { useAuth } from '../state/AuthContext.jsx';
import { Banner, Button, Card, EmptyState, Select, Spinner, TextInput } from '../components/ui.jsx';
import { Modal } from '../components/Modal.jsx';

const initials = (name = '?') => name.split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase();
function Avatar({ user }) { return <div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-teal-100 text-sm font-bold text-teal-700">{initials(user?.name)}</div>; }

export default function SharedExpensesView() {
  const { user } = useAuth();
  const [tab, setTab] = useState('friends');
  const [data, setData] = useState({ friends: [], incoming: [], outgoing: [], groups: [] });
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [friendOpen, setFriendOpen] = useState(false); const [groupOpen, setGroupOpen] = useState(false);
  const load = useCallback(async () => {
    setLoading(true); setError('');
    try { const [friends, groups] = await Promise.all([api.getFriends(), api.getGroups()]); setData({ ...friends, groups: groups.groups }); }
    catch (cause) { setError(cause.status === 401 ? 'Your session has expired. Please sign in again.' : 'Unable to connect to the server. Please try again.'); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { load(); }, [load]);
  const respond = async (id, accept) => { try { await (accept ? api.acceptFriendRequest(id) : api.rejectFriendRequest(id)); await load(); } catch (cause) { setError(cause.message); } };
  return <div className="mx-auto max-w-3xl space-y-5 pb-16">
    <section className="overflow-hidden rounded-[2rem] bg-gradient-to-br from-teal-600 via-teal-500 to-cyan-500 p-6 text-white shadow-lg shadow-teal-600/20"><p className="text-sm font-medium text-white/75">Shared expenses</p><div className="mt-1 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold tracking-tight">Hello, {user?.name?.split(' ')[0] || 'there'}</h1><p className="mt-1 text-sm text-white/80">People and groups you share with, in one place.</p></div><div className="flex gap-2"><Button className="bg-white text-teal-700 hover:bg-teal-50" icon={UserPlus} onClick={() => setFriendOpen(true)}>Add friend</Button><Button className="border border-white/30 bg-white/10 text-white hover:bg-white/20" icon={CirclePlus} onClick={() => setGroupOpen(true)}>New group</Button></div></div></section>
    {error && <Banner tone="error" title="Couldn’t update shared expenses">{error}</Banner>}
    <div className="flex rounded-2xl bg-slate-100 p-1 dark:bg-slate-900" role="tablist">{['friends', 'groups'].map((item) => <button key={item} type="button" role="tab" aria-selected={tab === item} onClick={() => setTab(item)} className={`flex-1 rounded-xl px-4 py-2.5 text-sm font-semibold capitalize ${tab === item ? 'bg-white text-teal-700 shadow-sm dark:bg-slate-800 dark:text-teal-300' : 'text-slate-500'}`}>{item}{item === 'friends' && data.incoming.length ? <span className="ml-2 rounded-full bg-teal-600 px-1.5 py-0.5 text-xs text-white">{data.incoming.length}</span> : null}</button>)}</div>
    {loading ? <div className="grid min-h-48 place-items-center"><Spinner size={28} className="text-teal-600" /></div> : tab === 'friends' ? <FriendsV2 data={data} onRespond={respond} onAdd={() => setFriendOpen(true)} /> : <Groups groups={data.groups} onAdd={() => setGroupOpen(true)} />}
    <FriendModalV2 open={friendOpen} close={() => setFriendOpen(false)} done={load} />
    <GroupModal open={groupOpen} close={() => setGroupOpen(false)} done={load} friends={data.friends} />
  </div>;
}

function Friends({ data, onRespond, onAdd }) { return <div className="space-y-4">
  {data.incoming.length > 0 && <Card className="overflow-hidden border-teal-100 p-0"><div className="border-b border-teal-100 bg-teal-50 px-5 py-3 text-sm font-bold text-teal-800">Friend requests</div>{data.incoming.map((request) => <div key={request.id} className="flex items-center gap-3 px-5 py-4"><Avatar user={request.fromUser} /><div className="min-w-0 flex-1"><p className="font-semibold text-slate-900 dark:text-slate-100">{request.fromUser?.name}</p><p className="truncate text-xs text-slate-500">{request.message || 'wants to share expenses with you'}</p></div><Button size="sm" variant="primary" className="bg-teal-600 hover:bg-teal-500" icon={Check} onClick={() => onRespond(request.id, true)}>Accept</Button><Button size="sm" variant="ghost" icon={X} aria-label="Reject request" onClick={() => onRespond(request.id, false)} /></div>)}</Card>}
  {data.friends.length === 0 ? <EmptyState icon={Users} title="You haven’t added anyone yet" description="Search registered users to create a real shared-expense relationship." action={<Button variant="primary" className="bg-teal-600 hover:bg-teal-500" onClick={onAdd}>Add friend</Button>} /> : <Card className="overflow-hidden p-0"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-3 dark:border-slate-800"><h2 className="text-sm font-bold">Your friends</h2><button type="button" className="text-xs font-bold text-teal-700" onClick={onAdd}>Add another</button></div>{data.friends.map((friend) => <div key={friend.id} className="flex items-center gap-3 border-b border-slate-100 px-5 py-4 last:border-0 dark:border-slate-800"><Avatar user={friend.user} /><div className="min-w-0 flex-1"><p className="font-semibold text-slate-900 dark:text-slate-100">{friend.user?.name}</p><p className="truncate text-xs text-slate-500">{friend.user?.email}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-500 dark:bg-slate-800">Ready to split</span></div>)}</Card>}
  {data.outgoing.length > 0 && <p className="px-2 text-xs text-slate-500">{data.outgoing.length} pending request{data.outgoing.length > 1 ? 's' : ''} waiting for acceptance.</p>}
</div>; }

function Groups({ groups, onAdd }) { if (!groups.length) return <EmptyState icon={FolderHeart} title="Create a group to start sharing expenses" description="Trips, homes, teams, and families each get a separate private ledger." action={<Button variant="primary" className="bg-teal-600 hover:bg-teal-500" onClick={onAdd}>Create group</Button>} />; return <div className="grid gap-4 sm:grid-cols-2">{groups.map((group) => <Card key={group.id} className="p-5"><div className="flex items-start gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-teal-50 text-xl">{group.icon || '✦'}</div><div><h2 className="font-bold text-slate-900 dark:text-slate-100">{group.name}</h2><p className="mt-0.5 text-xs text-slate-500">{group.members.length} members · {CURRENCIES[group.currency]?.code || group.currency}</p></div></div>{group.description && <p className="mt-4 text-sm text-slate-600 dark:text-slate-300">{group.description}</p>}<p className="mt-5 text-xs font-medium text-slate-400">Expense balances arrive in the next phase.</p></Card>)}</div>; }

function FriendModal({ open, close, done }) { const [query, setQuery] = useState(''); const [users, setUsers] = useState([]); const [note, setNote] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const search = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { setUsers((await api.searchUsers(query)).users); } catch (cause) { setError(cause.message); } finally { setBusy(false); } }; const send = async (id) => { setBusy(true); setError(''); try { await api.sendFriendRequest({ userId: id, message: note }); close(); done(); } catch (cause) { setError(cause.message); } finally { setBusy(false); } }; return <Modal open={open} onClose={close} title="Add a friend" subtitle="Find someone with an existing account." footer={<Button variant="ghost" onClick={close}>Close</Button>}><form onSubmit={search} className="space-y-4"><div className="flex gap-2"><TextInput data-autofocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name or email"/><Button type="submit" busy={busy} icon={Search}>Search</Button></div><TextInput value={note} onChange={(event) => setNote(event.target.value)} placeholder="Optional note" maxLength={200}/>{error && <p className="text-sm text-rose-600">{error}</p>}{users.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-2xl border border-slate-200 p-3 dark:border-slate-700"><Avatar user={item}/><div className="min-w-0 flex-1"><p className="font-semibold">{item.name}</p><p className="truncate text-xs text-slate-500">{item.email}</p></div><Button size="sm" className="bg-teal-600 hover:bg-teal-500" busy={busy} onClick={() => send(item.id)}>Request</Button></div>)}</form></Modal>; }

function GroupModal({ open, close, done, friends }) { const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [currency, setCurrency] = useState('INR'); const [chosen, setChosen] = useState([]); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const toggle = (id) => setChosen((ids) => ids.includes(id) ? ids.filter((value) => value !== id) : [...ids, id]); const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { await api.createGroup({ name, description, currency, memberIds: chosen }); close(); done(); } catch (cause) { setError(cause.message); } finally { setBusy(false); } }; return <Modal open={open} onClose={close} title="Create a group" subtitle="A private ledger for a trip, home, or team." footer={<><Button variant="ghost" onClick={close}>Cancel</Button><Button form="group-form" type="submit" busy={busy} className="bg-teal-600 hover:bg-teal-500">Create group</Button></>}><form id="group-form" onSubmit={submit} className="space-y-4"><TextInput data-autofocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Group name, e.g. Goa Trip" maxLength={60}/><textarea className="input min-h-24" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Description (optional)" maxLength={240}/><Select value={currency} onChange={(event) => setCurrency(event.target.value)}>{Object.values(CURRENCIES).map((item) => <option key={item.code} value={item.code}>{item.code} ({item.symbol})</option>)}</Select><div><p className="mb-2 text-sm font-semibold">Invite friends (optional)</p>{friends.length ? friends.map((friend) => <label key={friend.id} className="mb-2 flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><input type="checkbox" checked={chosen.includes(friend.user.id)} onChange={() => toggle(friend.user.id)}/><Avatar user={friend.user}/><span className="text-sm font-medium">{friend.user.name}</span></label>) : <p className="text-sm text-slate-500">Add friends first, or create the group for yourself.</p>}</div>{error && <p className="text-sm text-rose-600">{error}</p>}</form></Modal>; }

function FriendsV2({ data, onRespond, onAdd }) {
  const contacts = data.contacts || [];
  const none = !data.friends.length && !contacts.length;
  return <div className="space-y-4">
    {data.incoming.length > 0 && <Card className="overflow-hidden border-teal-100 p-0"><div className="border-b border-teal-100 bg-teal-50 px-4 py-3 text-sm font-bold text-teal-800">Friend requests</div>{data.incoming.map((request) => <div key={request.id} className="flex items-center gap-3 px-4 py-4"><Avatar user={request.fromUser} /><div className="min-w-0 flex-1"><p className="font-semibold text-slate-900 dark:text-slate-100">{request.fromUser?.name}</p><p className="truncate text-xs text-slate-500">{request.message || 'wants to share expenses with you'}</p></div><Button size="sm" variant="primary" className="bg-teal-600 hover:bg-teal-500" icon={Check} onClick={() => onRespond(request.id, true)}>Accept</Button><Button size="sm" variant="ghost" icon={X} aria-label="Reject request" onClick={() => onRespond(request.id, false)} /></div>)}</Card>}
    {none && <EmptyState icon={Users} title="Add someone to split with" description="They don’t need an account yet. Add them now and link automatically if they sign up later." action={<Button variant="primary" className="bg-teal-600 hover:bg-teal-500" onClick={onAdd}>Add friend</Button>} />}
    {data.friends.length > 0 && <Card className="overflow-hidden p-0"><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3 dark:border-slate-800"><h2 className="text-sm font-bold">Connected friends</h2><button type="button" className="text-xs font-bold text-teal-700" onClick={onAdd}>Add another</button></div>{data.friends.map((friend) => <div key={friend.id} className="flex items-center gap-3 border-b border-slate-100 px-4 py-4 last:border-0 dark:border-slate-800"><Avatar user={friend.user} /><div className="min-w-0 flex-1"><p className="font-semibold text-slate-900 dark:text-slate-100">{friend.user?.name}</p><p className="truncate text-xs text-slate-500">{friend.user?.email}</p></div><span className="rounded-full bg-teal-50 px-2.5 py-1 text-xs font-medium text-teal-700">Connected</span></div>)}</Card>}
    {contacts.length > 0 && <Card className="overflow-hidden p-0"><div className="border-b border-slate-100 px-4 py-3 dark:border-slate-800"><h2 className="text-sm font-bold">Private contacts</h2><p className="mt-0.5 text-xs text-slate-500">Their amounts are ready to link when they create an account.</p></div>{contacts.map((contact) => <div key={contact.id} className="flex items-center gap-3 border-b border-slate-100 px-4 py-4 last:border-0 dark:border-slate-800"><Avatar user={contact} /><div className="min-w-0 flex-1"><p className="font-semibold text-slate-900 dark:text-slate-100">{contact.name}</p><p className="truncate text-xs text-slate-500">{contact.email || 'No email added'}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${contact.linkedUserId ? 'bg-teal-50 text-teal-700' : 'bg-amber-50 text-amber-700'}`}>{contact.linkedUserId ? 'Connected' : 'Not registered'}</span></div>)}</Card>}
    {data.outgoing.length > 0 && <p className="px-2 text-xs text-slate-500">{data.outgoing.length} pending request{data.outgoing.length > 1 ? 's' : ''} waiting for acceptance.</p>}
  </div>;
}

function FriendModalV2({ open, close, done }) {
  const [mode, setMode] = useState('search'); const [query, setQuery] = useState(''); const [users, setUsers] = useState([]); const [note, setNote] = useState(''); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const search = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { setUsers((await api.searchUsers(query)).users); } catch (cause) { setError(cause.message); } finally { setBusy(false); } };
  const request = async (id) => { setBusy(true); setError(''); try { await api.sendFriendRequest({ userId: id, message: note }); close(); done(); } catch (cause) { setError(cause.message); } finally { setBusy(false); } };
  const createContact = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { await api.createContact({ name, email }); close(); done(); } catch (cause) { setError(cause.message); } finally { setBusy(false); } };
  return <Modal open={open} onClose={close} title="Add a friend" subtitle="Use an account now, or add a contact who can join later." footer={<Button variant="ghost" onClick={close}>Close</Button>}><div className="mb-5 grid grid-cols-2 rounded-xl bg-slate-100 p-1 dark:bg-slate-800"><button type="button" onClick={() => setMode('search')} className={`rounded-lg px-3 py-2 text-sm font-semibold ${mode === 'search' ? 'bg-white text-teal-700 shadow-sm dark:bg-slate-700' : 'text-slate-500'}`}>Has an account</button><button type="button" onClick={() => setMode('contact')} className={`rounded-lg px-3 py-2 text-sm font-semibold ${mode === 'contact' ? 'bg-white text-teal-700 shadow-sm dark:bg-slate-700' : 'text-slate-500'}`}>Add contact</button></div>{mode === 'search' ? <form onSubmit={search} className="space-y-4"><div className="flex gap-2"><TextInput data-autofocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name or email"/><Button type="submit" busy={busy} icon={Search}>Search</Button></div><TextInput value={note} onChange={(event) => setNote(event.target.value)} placeholder="Optional note" maxLength={200}/>{error && <p className="text-sm text-rose-600">{error}</p>}{users.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-2xl border border-slate-200 p-3 dark:border-slate-700"><Avatar user={item}/><div className="min-w-0 flex-1"><p className="font-semibold">{item.name}</p><p className="truncate text-xs text-slate-500">{item.email}</p></div><Button size="sm" className="bg-teal-600 hover:bg-teal-500" busy={busy} onClick={() => request(item.id)}>Request</Button></div>)}</form> : <form onSubmit={createContact} className="space-y-4"><p className="rounded-xl bg-teal-50 p-3 text-sm text-teal-800">No account needed. Add an email to connect this contact automatically when they register with it.</p><TextInput data-autofocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Friend’s name" maxLength={80}/><TextInput value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email (optional, for later linking)" type="email" maxLength={254}/>{error && <p className="text-sm text-rose-600">{error}</p>}<Button type="submit" className="w-full bg-teal-600 hover:bg-teal-500" busy={busy}>Add private contact</Button></form>}</Modal>;
}
